### ISSUE TITLE
unrecognized arguments: --oid 1

### ISSUE THREAD

**Issue by jxzeng-git** [ywchao/ho-rcnn#1]
@ywchao Hi, could you please help me, thank you very much
when I running detection with a trained mode according to [https://github.com/ywchao/ho-rcnn#running-detection-with-a-trained-model](url)
./experiments/scripts/test_rcnn_caffenet_ho_pconv_ip1_s/01_person.sh

the terminal output the information as the following:

+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ mkdir -p experiments/logs/test_rcnn_caffenet_ho_pconv_ip1_s/
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/test_rcnn_caffenet_ho_pconv_ip1_s/01_person.txt.2018-01-23_22-08-48
+ exec
++ tee -a experiments/logs/test_rcnn_caffenet_ho_pconv_ip1_s/01_person.txt.2018-01-23_22-08-48
+ echo Logging output to  experiments/logs/test_rcnn_caffenet_ho_pconv_ip1_s/01_person.txt.2018-01-23_22-08-48
Logging output to experiments/logs/test_rcnn_caffenet_ho_pconv_ip1_s/01_person.txt.2018-01-23_22-08-48
+ ./fast-rcnn/tools/test_net.py --gpu 0 --def ./models/rcnn_caffenet_ho_pconv_s/test_ip.prototxt --net ./output/ho_1_s/hico_det_train2015/rcnn_caffenet_pconv_ip_iter_150000.caffemodel --imdb hico_det_test2015 -
_-cfg ./experiments/cfgs/rcnn_ho_ip1_s.yml --oid 1
usage: test_net.py [-h] [--gpu GPU_ID] [--def PROTOTXT] [--net CAFFEMODEL]
                   [--cfg CFG_FILE] [--wait WAIT] [--imdb IMDB_NAME] [--comp]
                   [--set ...]_
test_net.py: error: **unrecognized arguments: --oid 1**

**Comment by jxzeng-git** [comment]
I comment it and everything be ok

**Comment by panfengli** [comment]
@SylviaZeng What is your train/valid/test split? I didn't find the config in the paper and codes.
