### ISSUE TITLE
How can I evaluate my results on HICO-DET?

### ISSUE THREAD

**Issue by MathiasHaudgaard** [ywchao/ho-rcnn#5]
I'm trying to evaluate my results on the hico-det dataset by running the evaluation code provided from the repo. However, I'm not quite sure how to do this. Can you give an explanation on how to do this?

**Comment by ywchao** [comment]
We have provided a [demo](https://github.com/ywchao/ho-rcnn#evaluation) for running the evaluation script on our result. To run on your result, you need to convert your result to the format we used in the demo, update the path to the result, and re-run the evaluation script.

**Comment by MathiasHaudgaard** [comment]
Thanks 😃
