### ISSUE TITLE
Definition of rare classes

### ISSUE THREAD

**Issue by baldassarreFe** [ywchao/ho-rcnn#6]
I'm trying to reproduce some results on the HICO-DET dataset, but I don't seem to find the correct split between rare and non-rare classes.

According to the paper, rare hoi classes are those having <5 instances in the training set. Rare classes should be 167 of the 600 hoi classes in total.

However, if I filter the training set using this criterion I find these counts:

```
count<k    num_hois
 5              100
 6              114
 7              123
 8              129
 9              132
10              138
11              144
12              154
13              159
14              164
15              168
16              174
17              178
18              183
19              187
20              190
```

I checked your [evaluation code](https://github.com/ywchao/ho-rcnn/blob/285cbffc316bd64c425b21b076fdd6ddce3c0a0e/evaluation/eval_one.m#L225-L236) and I spotted a `<10` in `eval_one.m`, but even with that threshold, the number 167 doesn't come up.

Can you provide a list of exactly which hoi categories you consider rare and which not?
A format similar to [the one you have on your website](https://drive.google.com/file/d/1ipvRTUF2zpOlHHqzbEb29iwscizoM1CK/view) would be ideal.

Thanks!

**Comment by ywchao** [comment]
The numbers you referred to ("<5 instances", "167 out of 600") should be for the HICO dataset (see ICCV'15). For HICO-DET (see WACV'18) the corresponding numbers should be "<10" and "138", which are exactly what you showed above.

**Comment by baldassarreFe** [comment]
Thanks for the quick reply!
I must have missed the new definition of rare classes in HICO-DET, I assumed it was the same as HICO. It's all clear now ;)
